name:                haskell-ctf-crypto
version:             0.1.0.0
github:              "tacopeland/haskell-ctf-crypto"
license:             BSD3
author:              "Timothy Copeland"
maintainer:          "timcopeland1111@gmail.com"
copyright:           "2021 Timothy Copeland"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tacopeland/haskell-ctf-crypto>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - bytestring
    - containers
    - integer-roots
    - parallel
    - random
    - split
  extra-deps:
    - git: git@github.com:martinra/hflint.git
      commit: 5c96ece2b72170b60f01632103f03f4654a0fb4e

tests:
  haskell-ctf-crypto-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-ctf-crypto
    - QuickCheck
